server:
  servlet:
    context-path: /computer-shop/

spring:
  liquibase:
    enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:h2:~/computer-shop
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
